import { typedFromEntries } from '@shared/types/utility.types'

/** all sextant modifiers. used for types and function parameters */
export const SEXTANT_MODIFIER = {
	// DELIRIUM
	MIRROR_OF_DELIRIUM: 'MIRROR_OF_DELIRIUM',
	DELIRIUM_REWARD: 'DELIRIUM_REWARD',

	// BEYOND
	BEYOND: 'BEYOND',

	// HARVEST
	SACRED_GROVE: 'SACRED_GROVE',
	BLUE_PLANTS: 'BLUE_PLANTS',
	PURPLE_PLANTS: 'PURPLE_PLANTS',
	YELLOW_PLANTS: 'YELLOW_PLANTS',

	// STRONGBOXES
	STRONGBOX_CORRUPTED: 'STRONGBOX_CORRUPTED',
	STRONGBOX_ENRAGED: 'STRONGBOX_ENRAGED',

	// HARBINGER
	MYSTERIOUS_HARBINGER: 'MYSTERIOUS_HARBINGER',

	// LEGION
	LEGION: 'LEGION',
	SPLINTERS_EMBLEMS_DUPLICATE: 'SPLINTERS_EMBLEMS_DUPLICATE',

	// MAPS
	MAP_8_MODIFIERS: 'MAP_8_MODIFIERS',
	MAP_20_QUALITY: 'MAP_20_QUALITY',
	MAGIC_PACK_SIZE: 'MAGIC_PACK_SIZE',
	RARE_PACKS: 'RARE_PACKS',
	MAP_QUALITY_TO_RARITY: 'MAP_QUALITY_TO_RARITY',
	PACK_SIZE_UNIDENTIFIED: 'PACK_SIZE_UNIDENTIFIED',

	// BOSS
	CONQUEROR_MAP: 'CONQUEROR_MAP',
	ELDER_GUARDIAN_MAP: 'ELDER_GUARDIAN_MAP',
	SHAPER_GUARDIAN_MAP: 'SHAPER_GUARDIAN_MAP',
	BOSS_DROP_UNIQUE: 'BOSS_DROP_UNIQUE',
	BOSS_DROP_VAAL: 'BOSS_DROP_VAAL',
	BODYGUARDS: 'BODYGUARDS',

	// BREACH
	BREACH: 'BREACH',
	ESH: 'ESH',
	XOPH: 'XOPH',
	TUL: 'TUL',
	UUL_NETOL: 'UUL_NETOL',
	CHAYULA: 'CHAYULA',

	// ABYSS
	ABYSS: 'ABYSS',

	// SHRINES
	RESONATING_SHRINE: 'RESONATING_SHRINE',
	GLOOM_SHRINE: 'GLOOM_SHRINE',

	// BLIGHT
	BLIGHT: 'BLIGHT',
	OILS_TIER: 'OILS_TIER',

	// RITUAL
	RITUAL_ALTARS: 'RITUAL_ALTARS',
	RITUAL_REROLLING: 'RITUAL_REROLLING',

	// HEIST
	SMUGGLERS_CACHE: 'SMUGGLERS_CACHE',
	CONTRACTS_IMPLICIT: 'CONTRACTS_IMPLICIT',

	// ESSENCE
	REMNANT_OF_CORRUPTION: 'REMNANT_OF_CORRUPTION',

	// ULTIMATUM
	ULTIMATUM: 'ULTIMATUM',

	// EXPEDITION
	RUNIC_MONSTER_MARKERS: 'RUNIC_MONSTER_MARKERS',

	// BEASTIARY
	EINHAR: 'EINHAR',
	COPY_OF_BEASTS: 'COPY_OF_BEASTS',

	// DELVE
	NIKO: 'NIKO',

	// INCURION
	ALVA: 'ALVA',

	// SYNDICATE
	JUN: 'JUN',
	SYNDICATE_INTELLIGENCE: 'SYNDICATE_INTELLIGENCE',

	// TORMENTED SPIRITS
	SPIRIT_RUSTED_SCARAB: 'SPIRIT_RUSTED_SCARAB',
	SPIRIT_POLISHED_SCARAB: 'SPIRIT_POLISHED_SCARAB',
	SPIRIT_GILDED_SCARAB: 'SPIRIT_GILDED_SCARAB',
	SPIRIT_UNIQUE: 'SPIRIT_UNIQUE',
	SPIRIT_MAP: 'SPIRIT_MAP',

	// ROGUE EXILES
	ROGUE_EXILES: 'ROGUE_EXILES',

	// ADDITIONAL PACKS
	INSTANT_FLASKS: 'INSTANT_FLASKS',
	CONVERT_MONSTERS: 'CONVERT_MONSTERS',
	CORRUPTED_GIFTS: 'CORRUPTED_GIFTS',
	VAAL_MONSTERS_CORRUPTED: 'VAAL_MONSTERS_CORRUPTED',
	CHAOS_MONSTERS: 'CHAOS_MONSTERS',
	PHYSICAL_MONSTERS: 'PHYSICAL_MONSTERS',
	LIGHTNING_MONSTERS: 'LIGHTNING_MONSTERS',
	COLD_MONSTERS: 'COLD_MONSTERS',
	FIRE_MONSTERS: 'FIRE_MONSTERS',
	REFLECTED: 'REFLECTED',

	// VAAL SKILLS
	SOUL_GAIN_PREVENTION: 'SOUL_GAIN_PREVENTION',
	SOUL_ON_KILL: 'SOUL_ON_KILL',

	// UNCATEGORIZED
	MYSTERIOUS_BARRELS: 'MYSTERIOUS_BARRELS',
	UNIQUE_MONSTERS_CORRUPTED: 'UNIQUE_MONSTERS_CORRUPTED',
	HUNTED_TRAITORS: 'HUNTED_TRAITORS',
	ALLURING: 'ALLURING',
	UNSUPPORTED: 'UNSUPPORTED',
} as const

export const SEXTANT_MODIFIER_IDX_TO_NAME = {
	0: 'MIRROR_OF_DELIRIUM',
	1: 'DELIRIUM_REWARD',
	2: 'BEYOND',
	3: 'SACRED_GROVE',
	4: 'BLUE_PLANTS',
	5: 'PURPLE_PLANTS',
	6: 'YELLOW_PLANTS',
	7: 'STRONGBOX_CORRUPTED',
	8: 'STRONGBOX_ENRAGED',
	9: 'MYSTERIOUS_HARBINGER',
	10: 'LEGION',
	11: 'SPLINTERS_EMBLEMS_DUPLICATE',
	12: 'MAP_8_MODIFIERS',
	13: 'MAP_20_QUALITY',
	14: 'MAGIC_PACK_SIZE',
	15: 'RARE_PACKS',
	16: 'MAP_QUALITY_TO_RARITY',
	17: 'PACK_SIZE_UNIDENTIFIED',
	18: 'CONQUEROR_MAP',
	19: 'ELDER_GUARDIAN_MAP',
	20: 'SHAPER_GUARDIAN_MAP',
	21: 'BOSS_DROP_UNIQUE',
	22: 'BOSS_DROP_VAAL',
	23: 'BODYGUARDS',
	24: 'BREACH',
	25: 'ESH',
	26: 'XOPH',
	27: 'TUL',
	28: 'UUL_NETOL',
	29: 'CHAYULA',
	30: 'ABYSS',
	31: 'RESONATING_SHRINE',
	32: 'GLOOM_SHRINE',
	33: 'BLIGHT',
	34: 'OILS_TIER',
	35: 'RITUAL_ALTARS',
	36: 'RITUAL_REROLLING',
	37: 'SMUGGLERS_CACHE',
	38: 'CONTRACTS_IMPLICIT',
	39: 'REMNANT_OF_CORRUPTION',
	40: 'ULTIMATUM',
	41: 'RUNIC_MONSTER_MARKERS',
	42: 'EINHAR',
	43: 'COPY_OF_BEASTS',
	44: 'NIKO',
	45: 'ALVA',
	46: 'JUN',
	47: 'SYNDICATE_INTELLIGENCE',
	48: 'SPIRIT_RUSTED_SCARAB',
	49: 'SPIRIT_POLISHED_SCARAB',
	50: 'SPIRIT_GILDED_SCARAB',
	51: 'SPIRIT_UNIQUE',
	52: 'SPIRIT_MAP',
	53: 'ROGUE_EXILES',
	54: 'INSTANT_FLASKS',
	55: 'CONVERT_MONSTERS',
	56: 'CORRUPTED_GIFTS',
	57: 'VAAL_MONSTERS_CORRUPTED',
	58: 'CHAOS_MONSTERS',
	59: 'PHYSICAL_MONSTERS',
	60: 'LIGHTNING_MONSTERS',
	61: 'COLD_MONSTERS',
	62: 'FIRE_MONSTERS',
	63: 'REFLECTED',
	64: 'SOUL_GAIN_PREVENTION',
	65: 'SOUL_ON_KILL',
	66: 'MYSTERIOUS_BARRELS',
	67: 'UNIQUE_MONSTERS_CORRUPTED',
	68: 'HUNTED_TRAITORS',
	69: 'ALLURING',
} as const

export const SEXTANT_MODIFIER_NAME_TO_IDX = typedFromEntries(
	Object.entries(SEXTANT_MODIFIER_IDX_TO_NAME).map(([key, value]) => [value, parseInt(key)])
)

/** secondary option for compasses */
export const SEXTANT_TYPE = {
	AWAKENED: 'AWAKENED',
	ELEVATED: 'ELEVATED',
} as const

export const SEXTANT_TIER_IDX_TO_NAME = {
	1: 'AWAKENED',
	2: 'ELEVATED',
} as const

export const SEXTANT_TIER_NAME_TO_IDX = {
	AWAKENED: 1,
	ELEVATED: 2,
} as const
