/** all sextant modifiers. used for types and function parameters */
export const SEXTANT_MODIFIER = {
	// DELIRIUM
	MIRROR_OF_DELIRIUM: 'MIRROR_OF_DELIRIUM',
	DELIRIUM_REWARD: 'DELIRIUM_REWARD',

	// RITUAL
	RITUAL_ALTARS: 'RITUAL_ALTARS',
	RITUAL_REROLLING: 'RITUAL_REROLLING',

	// HEIST
	SMUGGLERS_CACHE: 'SMUGGLERS_CACHE',
	CONTRACTS_IMPLICIT: 'CONTRACTS_IMPLICIT',

	// BEYOND
	BEYOND: 'BEYOND',

	// ABYSS
	ABYSS: 'ABYSS',

	// SHRINES
	RESONATING_SHRINE: 'RESONATING_SHRINE',
	GLOOM_SHRINE: 'GLOOM_SHRINE',

	// BLIGHT
	BLIGHT: 'BLIGHT',
	OILS_TIER: 'OILS_TIER',

	// BREACH
	BREACH: 'BREACH',
	ESH: 'ESH',
	XOPH: 'XOPH',
	TUL: 'TUL',
	UUL_NETOL: 'UUL_NETOL',
	CHAYULA: 'CHAYULA',

	// HARVEST
	SACRED_GROVE: 'SACRED_GROVE',
	BLUE_PLANTS: 'BLUE_PLANTS',
	PURPLE_PLANTS: 'PURPLE_PLANTS',
	YELLOW_PLANTS: 'YELLOW_PLANTS',

	// ESSENCE
	REMNANT_OF_CORRUPTION: 'REMNANT_OF_CORRUPTION',

	// ULTIMATUM
	ULTIMATUM: 'ULTIMATUM',

	// HARBINGER
	MYSTERIOUS_HARBINGER: 'MYSTERIOUS_HARBINGER',

	// LEGION
	LEGION: 'LEGION',
	SPLINTERS_EMBLEMS_DUPLICATE: 'SPLINTERS_EMBLEMS_DUPLICATE',

	// STRONGBOXES
	STRONGBOX_CORRUPTED: 'STRONGBOX_CORRUPTED',
	STRONGBOX_ENRAGED: 'STRONGBOX_ENRAGED',

	// EXPEDITION
	RUNIC_MONSTER_MARKERS: 'RUNIC_MONSTER_MARKERS',

	// BEASTIARY
	EINHAR: 'EINHAR',
	COPY_OF_BEASTS: 'COPY_OF_BEASTS',

	// DELVE
	NIKO: 'NIKO',

	// INCURION
	ALVA: 'ALVA',

	// SYNDICATE
	JUN: 'JUN',
	SYNDICATE_INTELLIGENCE: 'SYNDICATE_INTELLIGENCE',

	// MAPS
	MAP_8_MODIFIERS: 'MAP_8_MODIFIERS',
	MAP_20_QUALITY: 'MAP_20_QUALITY',
	MAGIC_PACK_SIZE: 'MAGIC_PACK_SIZE',
	RARE_PACKS: 'RARE_PACKS',
	MAP_QUALITY_TO_RARITY: 'MAP_QUALITY_TO_RARITY',
	PACK_SIZE_UNIDENTIFIED: 'PACK_SIZE_UNIDENTIFIED',

	// BOSS
	BOSS_DROP_UNIQUE: 'BOSS_DROP_UNIQUE',
	BOSS_DROP_VAAL: 'BOSS_DROP_VAAL',
	BODYGUARDS: 'BODYGUARDS',
	CONQUEROR_MAP: 'CONQUEROR_MAP',
	ELDER_GUARDIAN_MAP: 'ELDER_GUARDIAN_MAP',
	SHAPER_GUARDIAN_MAP: 'SHAPER_GUARDIAN_MAP',

	// TORMENTED SPIRITS
	SPIRIT_RUSTED_SCARAB: 'SPIRIT_RUSTED_SCARAB',
	SPIRIT_POLISHED_SCARAB: 'SPIRIT_POLISHED_SCARAB',
	SPIRIT_GILDED_SCARAB: 'SPIRIT_GILDED_SCARAB',
	SPIRIT_UNIQUE: 'SPIRIT_UNIQUE',
	SPIRIT_MAP: 'SPIRIT_MAP',

	// ROGUE EXILES
	ROGUE_EXILES: 'ROGUE_EXILES',

	// ADDITIONAL PACKS
	INSTANT_FLASKS: 'INSTANT_FLASKS',
	CONVERT_MONSTERS: 'CONVERT_MONSTERS',
	CORRUPTED_GIFTS: 'CORRUPTED_GIFTS',
	VAAL_MONSTERS_CORRUPTED: 'VAAL_MONSTERS_CORRUPTED',
	CHAOS_MONSTERS: 'CHAOS_MONSTERS',
	PHYSICAL_MONSTERS: 'PHYSICAL_MONSTERS',
	LIGHTNING_MONSTERS: 'LIGHTNING_MONSTERS',
	COLD_MONSTERS: 'COLD_MONSTERS',
	FIRE_MONSTERS: 'FIRE_MONSTERS',
	REFLECTED: 'REFLECTED',

	// VAAL SKILLS
	SOUL_GAIN_PREVENTION: 'SOUL_GAIN_PREVENTION',
	SOUL_ON_KILL: 'SOUL_ON_KILL',

	// UNCATEGORIZED
	MYSTERIOUS_BARRELS: 'MYSTERIOUS_BARRELS',
	UNIQUE_MONSTERS_CORRUPTED: 'UNIQUE_MONSTERS_CORRUPTED',
	HUNTED_TRAITORS: 'HUNTED_TRAITORS',
	ALLURING: 'ALLURING',
	UNSUPPORTED: 'UNSUPPORTED',
} as const

/** secondary option for compasses */
export const SEXTANT_TYPE = {
	AWAKENED: 'AWAKENED',
	ELEVATED: 'ELEVATED',
} as const
