import { typedFromEntries, getKeys } from '@shared/types/utility.types'

export const CATALYST_TYPE = {
	ABRASIVE_CATALYST: 'ABRASIVE_CATALYST',
	ACCELERATING_CATALYST: 'ACCELERATING_CATALYST',
	FERTILE_CATALYST: 'FERTILE_CATALYST',
	IMBUED_CATALYST: 'IMBUED_CATALYST',
	INTRINSIC_CATALYST: 'INTRINSIC_CATALYST',
	NOXIOUS_CATALYST: 'NOXIOUS_CATALYST',
	PRISMATIC_CATALYST: 'PRISMATIC_CATALYST',
	TAINTED_CATALYST: 'TAINTED_CATALYST',
	TEMPERING_CATALYST: 'TEMPERING_CATALYST',
	TURBULENT_CATALYST: 'TURBULENT_CATALYST',
	UNSTABLE_CATALYST: 'UNSTABLE_CATALYST',
} as const

export const CATALYST_TYPE_IDX_TO_NAME = getKeys(CATALYST_TYPE)

export const CATALYST_TYPE_NAME_TO_IDX = typedFromEntries(
	Object.entries(CATALYST_TYPE_IDX_TO_NAME).map(([key, value]) => [value, parseInt(key)])
)
