import { typedFromEntries, getKeys } from '@shared/types/utility.types'

export const MAP_TYPE = {
	ABOMINATION: 'ABOMINATION',
	ACADEMY: 'ACADEMY',
	ACID_CAVERNS: 'ACID_CAVERNS',
	"ACTON'S_NIGHTMARE": "ACTON'S_NIGHTMARE",
	'AL-HEZMIN,_THE_HUNTER': 'AL-HEZMIN,_THE_HUNTER',
	ALLEYWAYS: 'ALLEYWAYS',
	ALTERED_DISTANT_MEMORY: 'ALTERED_DISTANT_MEMORY',
	AUGMENTED_DISTANT_MEMORY: 'AUGMENTED_DISTANT_MEMORY',
	ANCIENT_CITY: 'ANCIENT_CITY',
	ARACHNID_NEST: 'ARACHNID_NEST',
	ARACHNID_TOMB: 'ARACHNID_TOMB',
	ARCADE: 'ARCADE',
	ARENA: 'ARENA',
	ARID_LAKE: 'ARID_LAKE',
	ARMOURY: 'ARMOURY',
	ARSENAL: 'ARSENAL',
	ASHEN_WOOD: 'ASHEN_WOOD',
	ATOLL: 'ATOLL',
	'BARAN,_THE_CRUSADER': 'BARAN,_THE_CRUSADER',
	BARROWS: 'BARROWS',
	BASILICA: 'BASILICA',
	BAZAAR: 'BAZAAR',
	BEACH: 'BEACH',
	BELFRY: 'BELFRY',
	BOG: 'BOG',
	BONE_CRYPT: 'BONE_CRYPT',
	BRAMBLE_VALLEY: 'BRAMBLE_VALLEY',
	BURIAL_CHAMBERS: 'BURIAL_CHAMBERS',
	"CAER_BLAIDD,_WOLFPACK'S_DEN": "CAER_BLAIDD,_WOLFPACK'S_DEN",
	CAGE: 'CAGE',
	CALDERA: 'CALDERA',
	CANYON: 'CANYON',
	CARCASS: 'CARCASS',
	CASTLE_RUINS: 'CASTLE_RUINS',
	CELLS: 'CELLS',
	CEMETERY: 'CEMETERY',
	CHANNEL: 'CHANNEL',
	CHATEAU: 'CHATEAU',
	CITADEL: 'CITADEL',
	CITY_SQUARE: 'CITY_SQUARE',
	COLD_RIVER: 'COLD_RIVER',
	COLONNADE: 'COLONNADE',
	COLOSSEUM: 'COLOSSEUM',
	CONSERVATORY: 'CONSERVATORY',
	CORAL_RUINS: 'CORAL_RUINS',
	CORE: 'CORE',
	CORTEX: 'CORTEX',
	COURTHOUSE: 'COURTHOUSE',
	COURTYARD: 'COURTYARD',
	COVES: 'COVES',
	CRATER: 'CRATER',
	CRIMSON_TEMPLE: 'CRIMSON_TEMPLE',
	CRIMSON_TOWNSHIP: 'CRIMSON_TOWNSHIP',
	CRYSTAL_ORE: 'CRYSTAL_ORE',
	CURSED_CRYPT: 'CURSED_CRYPT',
	DARK_FOREST: 'DARK_FOREST',
	DEATH_AND_TAXES: 'DEATH_AND_TAXES',
	DEFILED_CATHEDRAL: 'DEFILED_CATHEDRAL',
	DESERT: 'DESERT',
	DESERT_SPRING: 'DESERT_SPRING',
	DIG: 'DIG',
	"DORYANI'S_MACHINARIUM": "DORYANI'S_MACHINARIUM",
	'DROX,_THE_WARLORD': 'DROX,_THE_WARLORD',
	DRY_SEA: 'DRY_SEA',
	DUNES: 'DUNES',
	DUNGEON: 'DUNGEON',
	ENGRAVED_ULTIMATUM: 'ENGRAVED_ULTIMATUM',
	ESTUARY: 'ESTUARY',
	EXCAVATION: 'EXCAVATION',
	FACTORY: 'FACTORY',
	FIELDS: 'FIELDS',
	FLOODED_MINE: 'FLOODED_MINE',
	FORBIDDEN_WOODS: 'FORBIDDEN_WOODS',
	FORGE_OF_THE_PHOENIX: 'FORGE_OF_THE_PHOENIX',
	FORKING_RIVER: 'FORKING_RIVER',
	FORTRESS: 'FORTRESS',
	FOUNDRY: 'FOUNDRY',
	FROZEN_CABINS: 'FROZEN_CABINS',
	FUNGAL_HOLLOW: 'FUNGAL_HOLLOW',
	GARDENS: 'GARDENS',
	GEODE: 'GEODE',
	GHETTO: 'GHETTO',
	GLACIER: 'GLACIER',
	GRAVE_TROUGH: 'GRAVE_TROUGH',
	GRAVEYARD: 'GRAVEYARD',
	GROTTO: 'GROTTO',
	HALL_OF_GRANDMASTERS: 'HALL_OF_GRANDMASTERS',
	HALLOWED_GROUND: 'HALLOWED_GROUND',
	HARBINGER: 'HARBINGER',
	HAUNTED_MANSION: 'HAUNTED_MANSION',
	ICEBERG: 'ICEBERG',
	INFESTED_VALLEY: 'INFESTED_VALLEY',
	INFUSED_BEACHHEAD: 'INFUSED_BEACHHEAD',
	IVORY_TEMPLE: 'IVORY_TEMPLE',
	JUNGLE_VALLEY: 'JUNGLE_VALLEY',
	LABORATORY: 'LABORATORY',
	LAIR: 'LAIR',
	LAIR_OF_THE_HYDRA: 'LAIR_OF_THE_HYDRA',
	LAVA_CHAMBER: 'LAVA_CHAMBER',
	LAVA_LAKE: 'LAVA_LAKE',
	LEYLINE: 'LEYLINE',
	LIGHTHOUSE: 'LIGHTHOUSE',
	LOOKOUT: 'LOOKOUT',
	MAELSTRÖM_OF_CHAOS: 'MAELSTRÖM_OF_CHAOS',
	MALFORMATION: 'MALFORMATION',
	MAO_KUN: 'MAO_KUN',
	MARSHES: 'MARSHES',
	MAUSOLEUM: 'MAUSOLEUM',
	MAZE: 'MAZE',
	MAZE_OF_THE_MINOTAUR: 'MAZE_OF_THE_MINOTAUR',
	MESA: 'MESA',
	MINERAL_POOLS: 'MINERAL_POOLS',
	MOON_TEMPLE: 'MOON_TEMPLE',
	MUD_GEYSER: 'MUD_GEYSER',
	MUSEUM: 'MUSEUM',
	NECROPOLIS: 'NECROPOLIS',
	"OBA'S_CURSED_TROVE": "OBA'S_CURSED_TROVE",
	"OLMEC'S_SANCTUM": "OLMEC'S_SANCTUM",
	ORCHARD: 'ORCHARD',
	OVERGROWN_RUIN: 'OVERGROWN_RUIN',
	OVERGROWN_SHRINE: 'OVERGROWN_SHRINE',
	PALACE: 'PALACE',
	PARK: 'PARK',
	PEN: 'PEN',
	PENINSULA: 'PENINSULA',
	PHANTASMAGORIA: 'PHANTASMAGORIA',
	PIER: 'PIER',
	PILLARS_OF_ARUN: 'PILLARS_OF_ARUN',
	PIT: 'PIT',
	PIT_OF_THE_CHIMERA: 'PIT_OF_THE_CHIMERA',
	PLATEAU: 'PLATEAU',
	PLAZA: 'PLAZA',
	"POORJOY'S_ASYLUM": "POORJOY'S_ASYLUM",
	PORT: 'PORT',
	PRECINCT: 'PRECINCT',
	PRIMORDIAL_BLOCKS: 'PRIMORDIAL_BLOCKS',
	PRIMORDIAL_POOL: 'PRIMORDIAL_POOL',
	PROMENADE: 'PROMENADE',
	RACECOURSE: 'RACECOURSE',
	RAMPARTS: 'RAMPARTS',
	REEF: 'REEF',
	RELIC_CHAMBERS: 'RELIC_CHAMBERS',
	RESIDENCE: 'RESIDENCE',
	REWRITTEN_DISTANT_MEMORY: 'REWRITTEN_DISTANT_MEMORY',
	SANCTUARY: 'SANCTUARY',
	SCRIPTORIUM: 'SCRIPTORIUM',
	SEPULCHRE: 'SEPULCHRE',
	SHIPYARD: 'SHIPYARD',
	SHORE: 'SHORE',
	SHRINE: 'SHRINE',
	SIEGE: 'SIEGE',
	SILO: 'SILO',
	SPIDER_FOREST: 'SPIDER_FOREST',
	SPIDER_LAIR: 'SPIDER_LAIR',
	STAGNATION: 'STAGNATION',
	STRAND: 'STRAND',
	SULPHUR_VENTS: 'SULPHUR_VENTS',
	SUMMIT: 'SUMMIT',
	SUNKEN_CITY: 'SUNKEN_CITY',
	SYNTHESISED: 'SYNTHESISED',
	TEMPLE: 'TEMPLE',
	TERRACE: 'TERRACE',
	THE_BEACHHEAD: 'THE_BEACHHEAD',
	THE_CONSTRICTOR: 'THE_CONSTRICTOR',
	"THE_COWARD'S_TRIAL": "THE_COWARD'S_TRIAL",
	THE_ENSLAVER: 'THE_ENSLAVER',
	THE_ERADICATOR: 'THE_ERADICATOR',
	THE_PURIFIER: 'THE_PURIFIER',
	THE_PUTRID_CLOISTER: 'THE_PUTRID_CLOISTER',
	THE_SHAPERS_REALM: 'THE_SHAPERS_REALM',
	THE_TWILIGHT_TEMPLE: 'THE_TWILIGHT_TEMPLE',
	THE_VINKTAR_SQUARE: 'THE_VINKTAR_SQUARE',
	THICKET: 'THICKET',
	TOWER: 'TOWER',
	TOXIC_SEWER: 'TOXIC_SEWER',
	TROPICAL_ISLAND: 'TROPICAL_ISLAND',
	TWISTED_DISTANT_MEMORY: 'TWISTED_DISTANT_MEMORY',
	UNDERGROUND_RIVER: 'UNDERGROUND_RIVER',
	UNDERGROUND_SEA: 'UNDERGROUND_SEA',
	VAAL_PYRAMID: 'VAAL_PYRAMID',
	VAAL_TEMPLE: 'VAAL_TEMPLE',
	VAULT: 'VAULT',
	VAULTS_OF_ATZIRI: 'VAULTS_OF_ATZIRI',
	'VERITANIA,_THE_REDEEMER': 'VERITANIA,_THE_REDEEMER',
	VILLA: 'VILLA',
	VOLCANO: 'VOLCANO',
	WASTE_POOL: 'WASTE_POOL',
	WASTELAND: 'WASTELAND',
	WATERWAYS: 'WATERWAYS',
	WHAKAWAIRUA_TUAHU: 'WHAKAWAIRUA_TUAHU',
	WHARF: 'WHARF',
	ZIGGURAT: 'ZIGGURAT',
} as const

export const MAP_TYPE_IDX_TO_NAME = getKeys(MAP_TYPE)

export const MAP_TYPE_NAME_TO_IDX = typedFromEntries(
	Object.entries(MAP_TYPE_IDX_TO_NAME).map(([key, value]) => [value, parseInt(key)])
)

export const MAP_TIER = {
	TIER_1: 'TIER_1',
	TIER_2: 'TIER_2',
	TIER_3: 'TIER_3',
	TIER_4: 'TIER_4',
	TIER_5: 'TIER_5',
	TIER_6: 'TIER_6',
	TIER_7: 'TIER_7',
	TIER_8: 'TIER_8',
	TIER_9: 'TIER_9',
	TIER_10: 'TIER_10',
	TIER_11: 'TIER_11',
	TIER_12: 'TIER_12',
	TIER_13: 'TIER_13',
	TIER_14: 'TIER_14',
	TIER_15: 'TIER_15',
	TIER_16: 'TIER_16',
	TIER_17: 'TIER_17',
} as const

export const MAP_TIER_IDX_TO_NAME = getKeys(MAP_TIER)

export const MAP_TIER_NAME_TO_IDX = typedFromEntries(
	Object.entries(MAP_TIER_IDX_TO_NAME).map(([key, value]) => [value, parseInt(key)])
)

// MAP MODS

export const MAP_MODIFIERS = [
	'Slaying Enemies close together has a #% chance to attract monsters from Beyond',
	'#% more Magic Monsters',
	'#% increased number of Rare Monsters',
	"This Map's Modifiers to Quantity of Items found also apply to Rarity",
	'Area contains two Unique Bosses',
	'Area is inhabited by 2 additional Rogue Exiles',
	'Area contains many Totems',
	'Area is inhabited by Abominations',
	'Area is inhabited by Animals',
	'Area is inhabited by Demons',
	'Area is inhabited by Ghosts',
	'Area is inhabited by Goatmen',
	'Area is inhabited by Humanoids',
	'Area is inhabited by Cultists of Kitava',
	'Area is inhabited by Lunaris fanatics',
	'Area is inhabited by ranged monsters',
	'Area is inhabited by Skeletons',
	'Area is inhabited by Solaris fanatics',
	'Area is inhabited by Sea Witches and their Spawn',
	'Area is inhabited by Undead',
	'Area has increased monster variety',
	'Area has patches of desecrated ground',
	'Area has patches of Chilled Ground',
	'Area has patches of Burning Ground',
	'Monsters steal Power, Frenzy and Endurance charges on Hit',
	'Monsters Hinder on Hit with Spells',
	'Monsters Maim on Hit with Attacks',
	'Monsters Blind on Hit',
	'Monsters gain a Power Charge on Hit',
	'Monsters gain a Frenzy Charge on Hit',
	'Monsters gain an Endurance Charge on Hit',
	'Monsters have a #% chance to avoid Poison, Impale, and Bleeding',
	'Monsters fire 2 additional Projectiles',
	"Monsters' skills Chain 2 additional times",
	'Players are Cursed with Elemental Weakness',
	'Players are Cursed with Vulnerability',
	'Players have #% less Accuracy Rating',
	'Players have #% less Cooldown Recovery Rate',
	'Players have #% less Area of Effect',
	'Players gain #% reduced Flask Charges',
	'Buffs on Players expire #% faster',
	'Monsters take #% reduced Extra Damage from Critical Strikes',
	'Monsters have #% chance to Avoid Elemental Ailments',
	'Players have -#% to amount of Suppressed Spell Damage Prevented\n Monsters have #% increased Accuracy Rating',
	'Players have #% reduced Chance to Block Players have #% less Armour',
	'Monsters have +#% chance to Suppress Spell Damage',
	'#% less effect of Curses on Monsters',
	'+#% Monster Chaos Resistance\n +#% Monster Elemental Resistances',
	'+#% Monster Physical Damage Reduction',
	'Players cannot inflict Exposure',
	'#% more Monster Life',
	'Unique Boss has #% increased Life Unique Boss has #% increased Area of Effect',
	'Monsters gain #% of Maximum Life as Extra Maximum Energy Shield',
	'Area has patches of Consecrated Ground',
	'Monsters have #% increased Area of Effect',
	'Monsters have #% chance to Impale with Attacks',
	"Monsters' Action Speed cannot be modified to below base value\n Monsters cannot be Taunted",
	'Monsters Poison on Hit',
	'Monsters have a #% chance to cause Elemental Ailments on Hit',
	'#% increased Monster Movement Speed\n #% increased Monster Attack Speed\n #% increased Monster Cast Speed',
	'Monsters cannot be Stunned',
	'All Monster Damage from Hits always Ignites',
	'Area has patches of Shocked Ground which increase Damage taken by #%',
	'Monsters deal #% extra Physical Damage as Lightning',
	'Monsters deal #% extra Physical Damage as Fire',
	'Monsters deal #% extra Physical Damage as Cold',
	'#% increased Monster Damage',
	'Unique Boss deals #% increased Damage\n Unique Boss has #% increased Attack and Cast Speed',
	'Monsters have #% increased Critical Strike Chance\n +#% to Monster Critical Strike Multiplier',
	'Players are Cursed with Enfeeble',
	'Players have #% reduced effect of Non-Curse Auras from Skills',
	'Unique Bosses are Possessed',
	'Monsters are Hexproof',
	'Monsters deal #% extra Physical Damage as Chaos\n Monsters Inflict Withered for 2 seconds on Hit',
	'Players have #% less Recovery Rate of Life and Energy Shield',
	'Players have -#% to all maximum Resistances',
	'Players are Cursed with Temporal Chains',
	'Cannot Leech from Monsters',
	'Players cannot Regenerate Life, Mana or Energy Shield',
	'Monsters reflect #% of Physical Damage',
	'Monsters reflect #% of Elemental Damage',
]
