import { getKeys } from '@shared/types/utility.types'

// DO NOT CHANGE THE ORDER
export const DELI_ORB_TYPE = {
	ABYSSAL: 'ABYSSAL',
	ARMOURSMITHS: 'ARMOURSMITHS',
	BLACKSMITHS: 'BLACKSMITHS',
	BLIGHTED: 'BLIGHTED',
	CARTOGRAPHERS: 'CARTOGRAPHERS',
	DIVINERS: 'DIVINERS',
	FINE: 'FINE',
	FOREBODING: 'FOREBODING',
	FOSSILISED: 'FOSSILISED',
	FRAGMENTED: 'FRAGMENTED',
	JEWELLERS: 'JEWELLERS',
	OBSCURED: 'OBSCURED',
	SINGULAR: 'SINGULAR',
	SKITTERING: 'SKITTERING',
	THAUMATURGES: 'THAUMATURGES',
	TIMELESS: 'TIMELESS',
	WHISPERING: 'WHISPERING',
} as const

export const DELI_ORB_TYPE_IDX_TO_NAME = getKeys(DELI_ORB_TYPE)

export const DELI_ORB_TYPE_NAME_TO_IDX = DELI_ORB_TYPE_IDX_TO_NAME.reduce((prev, curr, idx) => {
	prev[curr] = idx
	return prev
}, {} as Record<keyof typeof DELI_ORB_TYPE, number>)
