import { getKeys, typedFromEntries } from '@shared/types/utility.types'

// DO NOT CHANGE THE ORDER
export const DELI_ORB_TYPE = {
	ABYSSAL_DELIRIUM_ORB: 'ABYSSAL_DELIRIUM_ORB',
	"ARMOURSMITH'S_DELIRIUM_ORB": "ARMOURSMITH'S_DELIRIUM_ORB",
	"BLACKSMITH'S_DELIRIUM_ORB": "BLACKSMITH'S_DELIRIUM_ORB",
	BLIGHTED_DELIRIUM_ORB: 'BLIGHTED_DELIRIUM_ORB',
	"CARTOGRAPHER'S_DELIRIUM_ORB": "CARTOGRAPHER'S_DELIRIUM_ORB",
	"DIVINER'S_DELIRIUM_ORB": "DIVINER'S_DELIRIUM_ORB",
	FINE_DELIRIUM_ORB: 'FINE_DELIRIUM_ORB',
	FOREBODING_DELIRIUM_ORB: 'FOREBODING_DELIRIUM_ORB',
	FOSSILISED_DELIRIUM_ORB: 'FOSSILISED_DELIRIUM_ORB',
	FRAGMENTED_DELIRIUM_ORB: 'FRAGMENTED_DELIRIUM_ORB',
	"JEWELLER'S_DELIRIUM_ORB": "JEWELLER'S_DELIRIUM_ORB",
	OBSCURED_DELIRIUM_ORB: 'OBSCURED_DELIRIUM_ORB',
	SINGULAR_DELIRIUM_ORB: 'SINGULAR_DELIRIUM_ORB',
	SKITTERING_DELIRIUM_ORB: 'SKITTERING_DELIRIUM_ORB',
	"THAUMATURGE'S_DELIRIUM_ORB": "THAUMATURGE'S_DELIRIUM_ORB",
	TIMELESS_DELIRIUM_ORB: 'TIMELESS_DELIRIUM_ORB',
	WHISPERING_DELIRIUM_ORB: 'WHISPERING_DELIRIUM_ORB',
} as const

export const DELI_ORB_TYPE_IDX_TO_NAME = getKeys(DELI_ORB_TYPE)

export const DELI_ORB_TYPE_NAME_TO_IDX = typedFromEntries(
	Object.entries(DELI_ORB_TYPE_IDX_TO_NAME).map(([key, value]) => [value, parseInt(key)])
)
